// AUTO-GENERATED by scripts/gen-image-manifest.mjs — do not edit by hand.
// Watch ids that have a /public/watches/<id>.png illustration.
export const IMAGE_READY = new Set<string>(["ap-code-15210qt","ap-code-15212nb","ap-ro-16202st","ap-ro-26240st","ap-ro-77450st","breguet-3357ba","cartier-tank-louis","chronoswiss-regulator","daniel-roth-447","fpjourne-bleu","lange-1-moonphase","lange-zeitwerk","mbf-lm101","omega-speedmaster","panerai-luminor","patek-nautilus-5711","vc-overseas-4500v","vc-patrimony-platinum"]);
