// AUTO-GENERATED by scripts/gen-image-manifest.mjs — do not edit by hand.
// Watch ids that have a /public/watches/<id>.png illustration.
export const IMAGE_READY = new Set<string>(["ap-code-15210qt","ap-code-15212nb","ap-ro-16202st","ap-ro-26240st","ap-ro-77450st","breguet-3357ba","daniel-roth-447","lange-1-moonphase","mbf-lm101","patek-nautilus-5711"]);
