// ----- Watch Knowledge Quiz (Game 4) -----
//
// Original multiple-choice questions authored for Watch Energy. The knowledge
// areas mirror a general horology syllabus (history, complications, movements,
// case & materials, brands, finishing/metiers d'art, terminology) — the
// questions themselves are written from scratch, not reproduced from any exam.
//
// Difficulty: 84 'easy' + 20 'hard'. Each round draws 10 questions, stratified
// as 8 easy + 2 hard (see drawQuiz). Option order is shuffled at runtime.
// Beginner-friendly by design; answers shown only as a final score.
//
// Ships behind FEATURES (staged launch, like the bracket). Not yet wired in.

export type QuizCategory =
  | "history"
  | "complications"
  | "movement"
  | "materials"
  | "brands"
  | "finishing"
  | "terminology";

export type QuizDifficulty = "easy" | "hard";

export interface QuizQuestion {
  id: string;
  category: QuizCategory;
  difficulty: QuizDifficulty;
  question: string;
  options: [string, string, string, string];
  answer: 0 | 1 | 2 | 3; // index into options
  explanation?: string;
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ---------------- EASY ----------------

  // History
  {
    id: "q001",
    category: "history",
    difficulty: "easy",
    question: "The Audemars Piguet Royal Oak (1972) was designed by which legendary designer?",
    options: ["Gerald Genta", "Max Busser", "Abraham-Louis Breguet", "George Daniels"],
    answer: 0,
    explanation: "Gerald Genta designed the Royal Oak, launched in 1972.",
  },
  {
    id: "q002",
    category: "history",
    difficulty: "easy",
    question: "Which country is the traditional heart of fine watchmaking, home to the Vallee de Joux?",
    options: ["Germany", "Switzerland", "France", "Japan"],
    answer: 1,
    explanation: "The Vallee de Joux in Switzerland is a cradle of haute horlogerie.",
  },
  {
    id: "q003",
    category: "history",
    difficulty: "easy",
    question: "The tourbillon was patented in 1801 by whom?",
    options: ["Abraham-Louis Breguet", "Hans Wilsdorf", "Antoine Norbert de Patek", "George Daniels"],
    answer: 0,
    explanation: "Breguet patented the tourbillon in 1801.",
  },
  {
    id: "q004",
    category: "history",
    difficulty: "easy",
    question: "Which Omega model was worn on the Moon during Apollo 11?",
    options: ["Seamaster", "Speedmaster", "Constellation", "De Ville"],
    answer: 1,
    explanation: "The Omega Speedmaster is the 'Moonwatch'.",
  },
  {
    id: "q005",
    category: "history",
    difficulty: "easy",
    question: "Which brand's 'Reverso' (1931) has a case that flips over to protect the dial?",
    options: ["Cartier", "Jaeger-LeCoultre", "Longines", "Rolex"],
    answer: 1,
    explanation: "The JLC Reverso was made to survive polo matches.",
  },
  {
    id: "q006",
    category: "history",
    difficulty: "easy",
    question: "The first commercial quartz wristwatch (1969) came from which country's industry?",
    options: ["Germany", "Japan", "USA", "France"],
    answer: 1,
    explanation: "Seiko's Astron (Japan, 1969) was the first commercial quartz watch.",
  },
  {
    id: "q007",
    category: "history",
    difficulty: "easy",
    question: "Rolex is headquartered in which Swiss city?",
    options: ["Bern", "Geneva", "Zurich", "Basel"],
    answer: 1,
    explanation: "Rolex is based in Geneva.",
  },
  {
    id: "q008",
    category: "history",
    difficulty: "easy",
    question: "The Cartier Santos (1904) is often credited as an early watch designed for what purpose?",
    options: ["Diving", "Aviation, to be worn by a pilot", "Motor racing", "Sailing"],
    answer: 1,
    explanation: "It was made for aviator Alberto Santos-Dumont.",
  },
  {
    id: "q009",
    category: "history",
    difficulty: "easy",
    question: "Patek Philippe was founded in which decade?",
    options: ["The 1830s", "The 1780s", "The 1920s", "The 1960s"],
    answer: 0,
    explanation: "Patek Philippe traces its founding to 1839.",
  },
  {
    id: "q010",
    category: "history",
    difficulty: "easy",
    question: "The Swatch watch, launched in 1983, helped rescue which country's watch industry?",
    options: ["Switzerland", "Japan", "Germany", "France"],
    answer: 0,
    explanation: "Swatch revived the Swiss industry after the quartz crisis.",
  },
  {
    id: "q011",
    category: "history",
    difficulty: "easy",
    question: "Abraham-Louis Breguet famously served royalty in which country, including Marie Antoinette?",
    options: ["England", "France", "Russia", "Austria"],
    answer: 1,
    explanation: "Breguet worked in Paris and served the French court.",
  },

  // Complications
  {
    id: "q012",
    category: "complications",
    difficulty: "easy",
    question: "A 'moonphase' complication displays what?",
    options: ["Temperature", "The phase of the Moon", "Heart rate", "Tide height"],
    answer: 1,
    explanation: "It tracks the waxing and waning of the Moon.",
  },
  {
    id: "q013",
    category: "complications",
    difficulty: "easy",
    question: "A 'chronograph' primarily lets a watch act as a what?",
    options: ["Second time zone", "Stopwatch", "Alarm", "Compass"],
    answer: 1,
    explanation: "A chronograph is a built-in stopwatch.",
  },
  {
    id: "q014",
    category: "complications",
    difficulty: "easy",
    question: "A 'perpetual calendar' automatically accounts for what?",
    options: ["Leap years and varying month lengths", "Daylight saving time", "Altitude", "Magnetism"],
    answer: 0,
    explanation: "It knows month lengths and leap years, often to 2100.",
  },
  {
    id: "q015",
    category: "complications",
    difficulty: "easy",
    question: "A 'GMT' watch is most useful for showing what?",
    options: ["Moon phase", "A second time zone", "A stopwatch", "Power reserve"],
    answer: 1,
    explanation: "A GMT hand tracks a second time zone.",
  },
  {
    id: "q016",
    category: "complications",
    difficulty: "easy",
    question: "A 'minute repeater' does what?",
    options: ["Vibrates silently", "Chimes the time on demand with gongs", "Repeats the date", "Counts laps"],
    answer: 1,
    explanation: "It chimes the hours, quarters and minutes on demand.",
  },
  {
    id: "q017",
    category: "complications",
    difficulty: "easy",
    question: "A 'power reserve indicator' shows what?",
    options: ["Water resistance", "How much running time is left before winding", "Battery percentage", "Altitude"],
    answer: 1,
    explanation: "It shows remaining stored energy.",
  },
  {
    id: "q018",
    category: "complications",
    difficulty: "easy",
    question: "A 'date window' on a watch shows what?",
    options: ["The day of the week only", "The day of the month", "The year", "The moon phase"],
    answer: 1,
    explanation: "A date aperture shows the calendar date.",
  },
  {
    id: "q019",
    category: "complications",
    difficulty: "easy",
    question: "A 'world time' complication typically displays what?",
    options: ["Only your local time", "The time across many time zones at once", "The date", "Sunrise time"],
    answer: 1,
    explanation: "Worldtimers show 24 zones / major cities together.",
  },
  {
    id: "q020",
    category: "complications",
    difficulty: "easy",
    question: "A 'jumping hour' display shows the hour how?",
    options: ["With a sweeping hand", "Instantly, in a jumping window", "On a subdial only", "In Roman numerals only"],
    answer: 1,
    explanation: "The hour snaps forward in an aperture.",
  },
  {
    id: "q021",
    category: "complications",
    difficulty: "easy",
    question: "A 'retrograde' hand does what?",
    options: ["Spins backward forever", "Sweeps an arc then snaps back to the start", "Glows in the dark", "Floats freely"],
    answer: 1,
    explanation: "It travels along an arc, then jumps back.",
  },
  {
    id: "q022",
    category: "complications",
    difficulty: "easy",
    question: "A COSC-certified 'chronometer' is a watch tested for what?",
    options: ["Water resistance", "High timekeeping accuracy", "Shock resistance", "Magnetism"],
    answer: 1,
    explanation: "Chronometer certification rates precision.",
  },

  // Movement
  {
    id: "q023",
    category: "movement",
    difficulty: "easy",
    question: "A manual-winding mechanical watch is powered by what?",
    options: ["A battery", "Sunlight", "A mainspring you wind by hand", "Body heat"],
    answer: 2,
    explanation: "Hand-winding tensions the mainspring.",
  },
  {
    id: "q024",
    category: "movement",
    difficulty: "easy",
    question: "An automatic (self-winding) watch winds itself using what?",
    options: ["Solar panels", "A rotor that turns with wrist motion", "A USB cable", "Friction heat"],
    answer: 1,
    explanation: "A swinging rotor winds the mainspring as you move.",
  },
  {
    id: "q025",
    category: "movement",
    difficulty: "easy",
    question: "The 'balance wheel' in a mechanical watch is best described as its what?",
    options: ["Power source", "Timekeeping oscillator (the heartbeat)", "Waterproof seal", "Date wheel"],
    answer: 1,
    explanation: "The balance oscillates to regulate timekeeping.",
  },
  {
    id: "q026",
    category: "movement",
    difficulty: "easy",
    question: "The 'escapement' in a mechanical watch does what?",
    options: ["Stores all the energy", "Releases energy in regular beats to keep time", "Seals out water", "Shows the date"],
    answer: 1,
    explanation: "It meters energy to the balance in steady ticks.",
  },
  {
    id: "q027",
    category: "movement",
    difficulty: "easy",
    question: "In a movement, '21 jewels' refers to what?",
    options: ["Gemstones for decoration", "Synthetic ruby bearings that reduce friction", "The price tier", "Diamonds on the dial"],
    answer: 1,
    explanation: "Jewel bearings cut friction at pivot points.",
  },
  {
    id: "q028",
    category: "movement",
    difficulty: "easy",
    question: "A higher beat rate (e.g. 28,800 vph) generally gives a watch what?",
    options: ["Longer battery life", "A smoother-sweeping seconds hand", "More water resistance", "A larger case"],
    answer: 1,
    explanation: "More beats per hour means a smoother sweep.",
  },
  {
    id: "q029",
    category: "movement",
    difficulty: "easy",
    question: "A 'quartz' watch keeps time using the vibrations of what?",
    options: ["A balance wheel", "A quartz crystal", "A pendulum", "A mainspring alone"],
    answer: 1,
    explanation: "A quartz crystal vibrates at a precise frequency.",
  },
  {
    id: "q030",
    category: "movement",
    difficulty: "easy",
    question: "The 'mainspring' of a mechanical watch is housed inside the what?",
    options: ["Rotor", "Barrel", "Balance", "Dial"],
    answer: 1,
    explanation: "The coiled mainspring sits inside the barrel.",
  },
  {
    id: "q031",
    category: "movement",
    difficulty: "easy",
    question: "'Hacking seconds' means the seconds hand does what when you pull the crown?",
    options: ["Spins faster", "Stops, so you can set the time precisely", "Glows", "Detaches"],
    answer: 1,
    explanation: "Stopping the seconds allows precise time setting.",
  },
  {
    id: "q032",
    category: "movement",
    difficulty: "easy",
    question: "A 'rotor' is the part that does what?",
    options: ["Shows the date", "Swings to wind an automatic watch", "Seals the case", "Holds the strap"],
    answer: 1,
    explanation: "The rotor's motion powers automatic winding.",
  },
  {
    id: "q033",
    category: "movement",
    difficulty: "easy",
    question: "'Shock protection' (e.g. Incabloc) mainly protects which delicate part?",
    options: ["The dial", "The balance staff and pivots", "The crystal", "The strap"],
    answer: 1,
    explanation: "It cushions the fragile balance pivots against knocks.",
  },

  // Case & Materials
  {
    id: "q034",
    category: "materials",
    difficulty: "easy",
    question: "Which precious metal is naturally white and never needs plating?",
    options: ["Platinum", "Brass", "Aluminium", "Bronze"],
    answer: 0,
    explanation: "Platinum is naturally white and very dense.",
  },
  {
    id: "q035",
    category: "materials",
    difficulty: "easy",
    question: "Rose gold gets its warm colour from being alloyed mainly with what?",
    options: ["Silver", "Copper", "Iron", "Tin"],
    answer: 1,
    explanation: "Copper gives rose gold its pinkish hue.",
  },
  {
    id: "q036",
    category: "materials",
    difficulty: "easy",
    question: "A sapphire crystal is prized mainly because it is highly what?",
    options: ["Flexible", "Scratch-resistant", "Lightweight", "Magnetic"],
    answer: 1,
    explanation: "Synthetic sapphire is extremely hard to scratch.",
  },
  {
    id: "q037",
    category: "materials",
    difficulty: "easy",
    question: "Titanium is popular for cases mainly because it is what?",
    options: ["Cheap", "Light and strong", "Magnetic", "Naturally gold-coloured"],
    answer: 1,
    explanation: "Titanium is light, strong and hypoallergenic.",
  },
  {
    id: "q038",
    category: "materials",
    difficulty: "easy",
    question: "A dive watch rated '300m' is suitable for what?",
    options: ["Only hand-washing", "Serious diving", "Spaceflight", "Decoration only"],
    answer: 1,
    explanation: "300m rating covers recreational and technical diving.",
  },
  {
    id: "q039",
    category: "materials",
    difficulty: "easy",
    question: "'PVD' / 'DLC' coatings are typically used to give a case what?",
    options: ["A see-through look", "A hard black (or coloured) finish", "Extra weight", "Magnetism"],
    answer: 1,
    explanation: "These coatings add a hard, dark surface finish.",
  },
  {
    id: "q040",
    category: "materials",
    difficulty: "easy",
    question: "A 'skeleton caseback' is usually made of what so you can see the movement?",
    options: ["Gold", "Sapphire crystal", "Rubber", "Ceramic"],
    answer: 1,
    explanation: "A sapphire caseback reveals the movement.",
  },
  {
    id: "q041",
    category: "materials",
    difficulty: "easy",
    question: "'Ceramic' is used in bezels and cases largely because it is what?",
    options: ["Soft", "Very scratch-resistant", "Magnetic", "Cheap"],
    answer: 1,
    explanation: "High-tech ceramic resists scratches and fading.",
  },
  {
    id: "q042",
    category: "materials",
    difficulty: "easy",
    question: "'Yellow, white and rose' are common varieties of which case metal?",
    options: ["Steel", "Gold", "Titanium", "Bronze"],
    answer: 1,
    explanation: "Gold is alloyed into yellow, white and rose tones.",
  },
  {
    id: "q043",
    category: "materials",
    difficulty: "easy",
    question: "'Bronze' watch cases are notable because they develop what over time?",
    options: ["Rust holes", "A patina", "Cracks", "Magnetism"],
    answer: 1,
    explanation: "Bronze gains a unique patina with wear.",
  },
  {
    id: "q044",
    category: "materials",
    difficulty: "easy",
    question: "'Mother-of-pearl' dials are made from what?",
    options: ["Painted plastic", "The iridescent inner shell of mollusks", "Crushed diamond", "Enamel"],
    answer: 1,
    explanation: "Nacre, the shell lining, gives a shimmering dial.",
  },

  // Brands
  {
    id: "q045",
    category: "brands",
    difficulty: "easy",
    question: "Which brand makes the 'Nautilus', designed by Gerald Genta in 1976?",
    options: ["Patek Philippe", "Rolex", "Omega", "Cartier"],
    answer: 0,
    explanation: "The Nautilus is Patek Philippe's sports icon.",
  },
  {
    id: "q046",
    category: "brands",
    difficulty: "easy",
    question: "A. Lange & Soehne, maker of the 'Lange 1', is based in which country?",
    options: ["Switzerland", "Germany", "Italy", "England"],
    answer: 1,
    explanation: "Lange is based in Glashutte, Germany.",
  },
  {
    id: "q047",
    category: "brands",
    difficulty: "easy",
    question: "Rolex was founded by whom?",
    options: ["Hans Wilsdorf", "Louis Cartier", "Edouard Heuer", "Georges Favre-Jacot"],
    answer: 0,
    explanation: "Hans Wilsdorf founded Rolex in the early 1900s.",
  },
  {
    id: "q048",
    category: "brands",
    difficulty: "easy",
    question: "The 'Submariner' dive watch belongs to which brand?",
    options: ["Omega", "Rolex", "Breitling", "Panerai"],
    answer: 1,
    explanation: "The Submariner is Rolex's classic diver.",
  },
  {
    id: "q049",
    category: "brands",
    difficulty: "easy",
    question: "Which brand makes the 'Royal Oak'?",
    options: ["Audemars Piguet", "Patek Philippe", "Vacheron Constantin", "Rolex"],
    answer: 0,
    explanation: "The Royal Oak is Audemars Piguet's flagship.",
  },
  {
    id: "q050",
    category: "brands",
    difficulty: "easy",
    question: "Vacheron Constantin, founded in 1755, is one of the oldest continuous makers from which country?",
    options: ["Germany", "Switzerland", "France", "Italy"],
    answer: 1,
    explanation: "Vacheron Constantin is a Geneva maison.",
  },
  {
    id: "q051",
    category: "brands",
    difficulty: "easy",
    question: "The 'Tank' watch is an icon of which maison?",
    options: ["Cartier", "Bvlgari", "Hermes", "Chanel"],
    answer: 0,
    explanation: "Cartier introduced the Tank in 1917.",
  },
  {
    id: "q052",
    category: "brands",
    difficulty: "easy",
    question: "'Grand Seiko' is the high-end line of which company?",
    options: ["Citizen", "Seiko", "Casio", "Orient"],
    answer: 1,
    explanation: "Grand Seiko is Seiko's luxury division.",
  },
  {
    id: "q053",
    category: "brands",
    difficulty: "easy",
    question: "What does the 'F.P.' stand for in F.P. Journe?",
    options: ["Francois-Paul", "Franz Peter", "Frederic Pierre", "Felix Patek"],
    answer: 0,
    explanation: "F.P. Journe is the independent Francois-Paul Journe.",
  },
  {
    id: "q054",
    category: "brands",
    difficulty: "easy",
    question: "Patek Philippe's famous campaign says you never truly own one, you merely what?",
    options: ["Rent it", "Look after it for the next generation", "Insure it", "Resell it"],
    answer: 1,
    explanation: "The 'Generations' slogan frames ownership as stewardship.",
  },
  {
    id: "q055",
    category: "brands",
    difficulty: "easy",
    question: "Omega is based in which country?",
    options: ["Switzerland", "Germany", "Japan", "Italy"],
    answer: 0,
    explanation: "Omega is a Swiss brand (Bienne).",
  },

  // Finishing / metiers d'art
  {
    id: "q056",
    category: "finishing",
    difficulty: "easy",
    question: "'Guilloche' refers to what?",
    options: ["Engraving fine repetitive patterns into a surface", "Painting enamel", "Diamond setting", "Mirror polishing"],
    answer: 0,
    explanation: "Guilloche is engine-turned decorative engraving.",
  },
  {
    id: "q057",
    category: "finishing",
    difficulty: "easy",
    question: "'Grand feu' enamel dials are finished by doing what?",
    options: ["3D printing", "Firing enamel in a kiln at high heat", "Spray painting", "Anodizing"],
    answer: 1,
    explanation: "Grand feu means 'great fire' kiln firing.",
  },
  {
    id: "q058",
    category: "finishing",
    difficulty: "easy",
    question: "'Cotes de Geneve' (Geneva stripes) is a form of what?",
    options: ["A complication", "Decorative movement finishing", "A strap material", "A case shape"],
    answer: 1,
    explanation: "It is a striped decoration on movement bridges.",
  },
  {
    id: "q059",
    category: "finishing",
    difficulty: "easy",
    question: "'Skeletonization' of a watch means what?",
    options: ["Making it waterproof", "Cutting away material to reveal the movement", "Adding gemstones", "Coating it black"],
    answer: 1,
    explanation: "Skeletonizing opens up the movement to view.",
  },
  {
    id: "q060",
    category: "finishing",
    difficulty: "easy",
    question: "'Anglage' (beveling) is the craft of what?",
    options: ["Setting stones", "Polishing the chamfered edges of movement parts", "Painting the dial", "Shaping the case"],
    answer: 1,
    explanation: "Anglage polishes the chamfers of bridges and parts.",
  },
  {
    id: "q061",
    category: "finishing",
    difficulty: "easy",
    question: "A 'fume' (smoked) dial typically features what?",
    options: ["A burnt scent", "A colour that darkens gradually toward the edges", "Real smoke sealed inside", "A flat matte black"],
    answer: 1,
    explanation: "A fume dial fades from light centre to dark rim.",
  },
  {
    id: "q062",
    category: "finishing",
    difficulty: "easy",
    question: "'Polishing' a watch surface aims to make it what?",
    options: ["Rough", "Smooth and mirror-like", "Matte", "Magnetic"],
    answer: 1,
    explanation: "Polishing creates a bright mirror finish.",
  },
  {
    id: "q063",
    category: "finishing",
    difficulty: "easy",
    question: "'Brushed' (satin) finishing gives a surface what?",
    options: ["A mirror shine", "Fine parallel lines and a soft sheen", "Diamonds", "Bright colour"],
    answer: 1,
    explanation: "Brushing leaves a directional satin texture.",
  },
  {
    id: "q064",
    category: "finishing",
    difficulty: "easy",
    question: "An 'applied' hour marker is one that is what?",
    options: ["Printed flat", "A separate metal piece attached to the dial", "Painted by hand", "Engraved into the case"],
    answer: 1,
    explanation: "Applied markers are individually fixed to the dial.",
  },
  {
    id: "q065",
    category: "finishing",
    difficulty: "easy",
    question: "'Enamel' dials are admired for their what?",
    options: ["Plastic feel", "Deep, long-lasting colour and glassy finish", "Low cost", "Magnetism"],
    answer: 1,
    explanation: "Enamel keeps its colour and gloss for generations.",
  },
  {
    id: "q066",
    category: "finishing",
    difficulty: "easy",
    question: "'Engraving' on a watch is the art of what?",
    options: ["3D printing", "Cutting designs into metal by hand or machine", "Painting", "Coating"],
    answer: 1,
    explanation: "Engraving incises decoration into metal.",
  },

  // Terminology
  {
    id: "q067",
    category: "terminology",
    difficulty: "easy",
    question: "'Haute horlogerie' roughly translates to what?",
    options: ["Cheap quartz", "High / fine watchmaking", "Smartwatches", "Pocket watches only"],
    answer: 1,
    explanation: "It means 'high watchmaking'.",
  },
  {
    id: "q068",
    category: "terminology",
    difficulty: "easy",
    question: "A watch's 'lug-to-lug' measurement describes what?",
    options: ["Strap colour", "The length across the case from one lug tip to the other", "Water resistance", "Movement frequency"],
    answer: 1,
    explanation: "Lug-to-lug affects how a watch sits on the wrist.",
  },
  {
    id: "q069",
    category: "terminology",
    difficulty: "easy",
    question: "An 'in-house movement' is one that was what?",
    options: ["Bought from a supplier", "Designed and made by the watch brand itself", "Assembled at home", "3D printed"],
    answer: 1,
    explanation: "In-house means developed and built by the brand.",
  },
  {
    id: "q070",
    category: "terminology",
    difficulty: "easy",
    question: "A 'NATO strap' is typically what?",
    options: ["Solid gold", "A single-piece woven nylon band", "Ceramic", "Leather only"],
    answer: 1,
    explanation: "A NATO is a one-piece nylon strap.",
  },
  {
    id: "q071",
    category: "terminology",
    difficulty: "easy",
    question: "'Bezel' refers to which part of a watch?",
    options: ["The strap", "The ring around the crystal and dial", "The crown", "The caseback"],
    answer: 1,
    explanation: "The bezel frames the crystal.",
  },
  {
    id: "q072",
    category: "terminology",
    difficulty: "easy",
    question: "The 'crown' is the part you use to do what?",
    options: ["Read the date", "Wind and set the watch", "Open the caseback", "Attach the strap"],
    answer: 1,
    explanation: "The crown winds and sets the watch.",
  },
  {
    id: "q073",
    category: "terminology",
    difficulty: "easy",
    question: "'Lug' refers to what?",
    options: ["The dial", "The parts of the case where the strap attaches", "The crystal", "The rotor"],
    answer: 1,
    explanation: "Lugs hold the strap or bracelet.",
  },
  {
    id: "q074",
    category: "terminology",
    difficulty: "easy",
    question: "'Caliber' (calibre) generally refers to a watch's what?",
    options: ["Strap size", "Movement (its model or type)", "Water rating", "Price"],
    answer: 1,
    explanation: "A calibre is a specific movement.",
  },
  {
    id: "q075",
    category: "terminology",
    difficulty: "easy",
    question: "A 'complication' means any function beyond what?",
    options: ["The brand name", "Simply telling the time", "The strap", "Water resistance"],
    answer: 1,
    explanation: "Anything beyond basic timekeeping is a complication.",
  },
  {
    id: "q076",
    category: "terminology",
    difficulty: "easy",
    question: "A 'dress watch' usually describes a watch that is what?",
    options: ["Big and sporty", "Thin, elegant and simple, for formal wear", "A dive watch", "A smartwatch"],
    answer: 1,
    explanation: "Dress watches are slim and understated.",
  },
  {
    id: "q077",
    category: "terminology",
    difficulty: "easy",
    question: "A 'reference number' on a watch identifies its what?",
    options: ["Owner", "Specific model and configuration", "Service date", "Resale price"],
    answer: 1,
    explanation: "The reference pins down the exact model.",
  },
  {
    id: "q078",
    category: "terminology",
    difficulty: "easy",
    question: "'Water resistant 50m' generally means a watch is okay for what?",
    options: ["Scuba diving", "Splashes and brief swimming", "Deep diving", "Nothing at all"],
    answer: 1,
    explanation: "50m suits everyday splashes and light swimming.",
  },

  // A few extra easy to balance categories
  {
    id: "q079",
    category: "movement",
    difficulty: "easy",
    question: "'Power reserve' refers to what?",
    options: ["Spare batteries", "How long a fully wound watch keeps running", "Water resistance", "Warranty length"],
    answer: 1,
    explanation: "It is the running time on a full wind.",
  },
  {
    id: "q080",
    category: "complications",
    difficulty: "easy",
    question: "An 'annual calendar' needs manual correction only once a year, at the end of which month?",
    options: ["December", "February", "June", "March"],
    answer: 1,
    explanation: "It cannot track February's short length, so you fix it then.",
  },
  {
    id: "q081",
    category: "complications",
    difficulty: "easy",
    question: "A 'flyback' chronograph lets you do what?",
    options: ["Reset and restart the timing in a single press", "Show a second time zone", "Glow brightly", "Add a date"],
    answer: 0,
    explanation: "One press resets and restarts timing instantly.",
  },
  {
    id: "q082",
    category: "history",
    difficulty: "easy",
    question: "The 1970s 'Quartz Crisis' caused major hardship for the watch industry of which country?",
    options: ["Japan", "Switzerland", "USA", "China"],
    answer: 1,
    explanation: "Cheap quartz nearly wiped out Swiss mechanical makers.",
  },
  {
    id: "q083",
    category: "materials",
    difficulty: "easy",
    question: "'Stainless steel' is the most common case material mainly because it is what?",
    options: ["The most precious", "Durable, corrosion-resistant and affordable", "The lightest", "Transparent"],
    answer: 1,
    explanation: "Steel balances toughness, looks and cost.",
  },
  {
    id: "q084",
    category: "brands",
    difficulty: "easy",
    question: "The 'Lange 1', with its off-centre dial, is a flagship of which brand?",
    options: ["Glashutte Original", "A. Lange & Soehne", "Nomos", "Stowa"],
    answer: 1,
    explanation: "The Lange 1 is A. Lange & Soehne's signature.",
  },

  // ---------------- HARD ----------------

  {
    id: "h01",
    category: "history",
    difficulty: "hard",
    question: "The Gerald Genta and Daniel Roth brands were both absorbed in 2000 by which group?",
    options: ["Swatch Group", "Richemont", "Bulgari", "LVMH"],
    answer: 2,
    explanation: "Bulgari acquired both in 2000, later folding them into Bulgari Haute Horlogerie.",
  },
  {
    id: "h02",
    category: "history",
    difficulty: "hard",
    question: "George Daniels is celebrated for inventing which escapement, later adopted by Omega?",
    options: ["Lever", "Co-axial", "Detente", "Cylinder"],
    answer: 1,
    explanation: "The co-axial escapement reduces sliding friction.",
  },
  {
    id: "h03",
    category: "history",
    difficulty: "hard",
    question: "Which English watchmaker hand-built watches and wrote the key reference text 'Watchmaking'?",
    options: ["George Daniels", "Max Busser", "F.P. Journe", "Hans Wilsdorf"],
    answer: 0,
    explanation: "George Daniels authored the seminal book 'Watchmaking'.",
  },
  {
    id: "h04",
    category: "brands",
    difficulty: "hard",
    question: "The 'Calatrava cross' is the logo of which maison?",
    options: ["Vacheron Constantin", "Patek Philippe", "Breguet", "A. Lange & Soehne"],
    answer: 1,
    explanation: "The Calatrava cross is Patek Philippe's emblem.",
  },
  {
    id: "h05",
    category: "brands",
    difficulty: "hard",
    question: "The fine 'L.U.C' movement line belongs to which maison?",
    options: ["Chopard", "Chaumet", "Corum", "Cartier"],
    answer: 0,
    explanation: "L.U.C is Chopard's in-house haute horlogerie line.",
  },
  {
    id: "h06",
    category: "complications",
    difficulty: "hard",
    question: "A 'rattrapante' chronograph is better known as a what?",
    options: ["Flyback", "Split-seconds", "Foudroyante", "Regulator"],
    answer: 1,
    explanation: "A rattrapante times two events at once (split-seconds).",
  },
  {
    id: "h07",
    category: "complications",
    difficulty: "hard",
    question: "An 'equation of time' complication shows the difference between what?",
    options: ["Two time zones", "Mean solar time and true solar time", "Day and night length", "Atomic and sidereal time"],
    answer: 1,
    explanation: "It tracks the gap between clock time and real sun time.",
  },
  {
    id: "h08",
    category: "complications",
    difficulty: "hard",
    question: "A 'foudroyante' (jumping) hand typically does what?",
    options: ["Runs once a minute", "Whirls around a small dial once per second to mark fractions", "Counts hours", "Shows the date"],
    answer: 1,
    explanation: "The foudroyante spins each second to show fractions.",
  },
  {
    id: "h09",
    category: "complications",
    difficulty: "hard",
    question: "The tourbillon was originally devised to improve accuracy in which watches, sitting in one position?",
    options: ["Dive watches", "Pocket watches", "Quartz watches", "Smartwatches"],
    answer: 1,
    explanation: "Pocket watches sat vertically; the tourbillon averaged out gravity.",
  },
  {
    id: "h10",
    category: "movement",
    difficulty: "hard",
    question: "A 'free-sprung' balance regulates rate by adjusting what, instead of an index?",
    options: ["The mainspring", "Weights or screws on the balance wheel", "The rotor", "The escape wheel"],
    answer: 1,
    explanation: "Adjustable masses on the balance set the rate.",
  },
  {
    id: "h11",
    category: "movement",
    difficulty: "hard",
    question: "A 'Breguet overcoil' is a special shape of which component?",
    options: ["The rotor", "The balance spring (hairspring)", "The mainspring", "The escape wheel"],
    answer: 1,
    explanation: "The overcoil raises the hairspring's outer turn for better isochronism.",
  },
  {
    id: "h12",
    category: "movement",
    difficulty: "hard",
    question: "A 'detente' (chronometer) escapement is accurate but fragile against what?",
    options: ["Water", "Shocks and jolts", "Heat", "Magnetism"],
    answer: 1,
    explanation: "Its sensitivity to shock kept it mostly in marine chronometers.",
  },
  {
    id: "h13",
    category: "movement",
    difficulty: "hard",
    question: "A 'remontoire' inside a movement is designed to deliver what?",
    options: ["A louder chime", "Constant force to the escapement", "A second time zone", "A bigger case"],
    answer: 1,
    explanation: "A remontoire evens out the force reaching the escapement.",
  },
  {
    id: "h14",
    category: "materials",
    difficulty: "hard",
    question: "'Tantalum', a rare case metal used by some independents, is distinctive for its what?",
    options: ["Pure white shine", "Bluish-grey hue and high density", "Light weight", "Transparency"],
    answer: 1,
    explanation: "Tantalum has a heavy, blue-grey character.",
  },
  {
    id: "h15",
    category: "materials",
    difficulty: "hard",
    question: "Silicon hairsprings are prized mainly because silicon is what?",
    options: ["Heavier", "Anti-magnetic and low-friction", "Cheaper to hand-finish", "Naturally gold-toned"],
    answer: 1,
    explanation: "Silicon resists magnetism and needs no lubrication.",
  },
  {
    id: "h16",
    category: "materials",
    difficulty: "hard",
    question: "A 'Nivarox'-type hairspring alloy is designed mainly to resist what?",
    options: ["Water", "Temperature changes and magnetism", "Scratches", "Light"],
    answer: 1,
    explanation: "Such alloys keep the rate stable across temperature and fields.",
  },
  {
    id: "h17",
    category: "finishing",
    difficulty: "hard",
    question: "'Black polishing' (poli noir) makes a surface appear how?",
    options: ["Matte grey", "Black from one angle and mirror-bright from another", "Brushed", "Frosted"],
    answer: 1,
    explanation: "A perfectly flat polish reflects black or bright by angle.",
  },
  {
    id: "h18",
    category: "finishing",
    difficulty: "hard",
    question: "The highest hand-finishing, as in Philippe Dufour's work, is prized for finishing even what?",
    options: ["The strap", "The hidden, unseen surfaces of the movement", "The box", "The dial printing"],
    answer: 1,
    explanation: "Top finishing treats surfaces no owner will ever see.",
  },
  {
    id: "h19",
    category: "terminology",
    difficulty: "hard",
    question: "The 'Geneva Seal' (Poincon de Geneve) certifies watches crafted in what area?",
    options: ["Anywhere in Switzerland", "The Canton of Geneva", "The Vallee de Joux", "Glashutte"],
    answer: 1,
    explanation: "It is a regional quality hallmark for Geneva.",
  },
  {
    id: "h20",
    category: "terminology",
    difficulty: "hard",
    question: "A movement beating at '5 Hz' runs at how many vibrations per hour?",
    options: ["28,800", "36,000", "21,600", "18,000"],
    answer: 1,
    explanation: "5 Hz = 10 beats per second = 36,000 vph.",
  },
];

// ----- Draw + scoring -----

function shuffle<T>(arr: readonly T[]): T[] {
  const out = arr.slice();
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

export interface DrawnQuestion extends QuizQuestion {
  shuffledOptions: string[];
  shuffledAnswer: number; // index into shuffledOptions
}

// Stratified draw: `total` questions with `hardCount` of them 'hard'.
// Option order is shuffled per question so the correct slot is unpredictable.
export function drawQuiz(total = 10, hardCount = 2): DrawnQuestion[] {
  const easy = QUIZ_QUESTIONS.filter((q) => q.difficulty === "easy");
  const hard = QUIZ_QUESTIONS.filter((q) => q.difficulty === "hard");

  const pickedHard = shuffle(hard).slice(0, Math.min(hardCount, hard.length));
  const pickedEasy = shuffle(easy).slice(0, Math.max(0, total - pickedHard.length));

  return shuffle([...pickedEasy, ...pickedHard]).map((q) => {
    const order = shuffle([0, 1, 2, 3]);
    const shuffledOptions = order.map((i) => q.options[i]);
    return {
      ...q,
      shuffledOptions,
      shuffledAnswer: order.indexOf(q.answer),
    };
  });
}

export interface QuizTitle {
  title: string;
  min: number; // inclusive lower bound of score (out of 10)
}

export const QUIZ_TITLES: QuizTitle[] = [
  { title: "Master Horologist", min: 9 },
  { title: "Seasoned Collector", min: 7 },
  { title: "Enthusiast", min: 4 },
  { title: "Curious Newcomer", min: 0 },
];

export function scoreToTitle(score: number): string {
  return (QUIZ_TITLES.find((t) => score >= t.min) ?? QUIZ_TITLES[QUIZ_TITLES.length - 1]).title;
}
