import type { Watch } from "./types";

// Energy tagging follows the affinity tables in the engine:
//   case metal  -> caseEnergy   |   dial colour -> dialEnergy
//   VERDANT: titanium / green · skeleton (motion)
//   EMBER:   rose-gold / salmon
//   TERRA:   yellow-gold · warm ceramic / champagne-warm silver
//   LUMEN:   steel · white-gold · platinum / white · cool silver
//   TIDE:    dark ceramic / blue · black · aventurine · smoked
//
// Horological facts vetted against the accuracy guardrails (Genta, Breguet 1801
// patent, 16202 vs 15202, Spring Drive, sonnerie au passage, etc.).

export const WATCHES: Watch[] = [
  // ---------- The real collection ----------
  {
    id: "ap-ro-16202st",
    brand: "Audemars Piguet",
    model: "Royal Oak Jumbo Extra-Thin",
    reference: "16202ST",
    caseMaterial: "Stainless steel",
    dialColor: "Blue",
    caseEnergy: "LUMEN",
    dialEnergy: "TIDE",
    signature: "Sharp, composed confidence with nothing left to prove.",
    fact: "The 16202 succeeded the 15202 in 2022 with the new in-house calibre 7121.",
    owned: true,
    rarity: 18,
    metal: "steel",
    dialHex: "#27508c",
    complication: "time",
  },
  {
    id: "ap-ro-26240st",
    brand: "Audemars Piguet",
    model: "Royal Oak Selfwinding Chronograph",
    reference: "26240ST",
    caseMaterial: "Stainless steel",
    dialColor: "Green",
    caseEnergy: "LUMEN",
    dialEnergy: "VERDANT",
    signature: "Restless drive channelled into clean, deliberate motion.",
    fact: "The 41mm 26240 chronograph refined the integrated bracelet end-links in 2021.",
    owned: true,
    rarity: 16,
    metal: "steel",
    dialHex: "#2f5d4a",
    complication: "chronograph",
  },
  {
    id: "ap-ro-77450st",
    brand: "Audemars Piguet",
    model: "Royal Oak Selfwinding",
    reference: "77450ST",
    caseMaterial: "Stainless steel",
    dialColor: "White",
    caseEnergy: "LUMEN",
    dialEnergy: "LUMEN",
    signature: "Quiet poise that lets the architecture speak.",
    fact: "The 34mm 77450 sits within AP's broader, less gendered modern line-up.",
    owned: true,
    rarity: 20,
    metal: "steel",
    dialHex: "#e9e7df",
    complication: "time",
  },
  {
    id: "ap-code-15210qt",
    brand: "Audemars Piguet",
    model: "Code 11.59 Selfwinding",
    reference: "15210QT",
    caseMaterial: "Steel & black ceramic",
    dialColor: "Smoked grey",
    caseEnergy: "LUMEN",
    dialEnergy: "TIDE",
    signature: "Modern duality — an industrial edge wrapped around warmth.",
    fact: "Its double-curved sapphire is convex on both faces, correcting lateral distortion.",
    owned: true,
    rarity: 13,
    metal: "steelCeramic",
    dialHex: "#3a3a40",
    complication: "time",
  },
  {
    id: "ap-code-15212nb",
    brand: "Audemars Piguet",
    model: "Code 11.59 Starwheel",
    reference: "15212NB",
    caseMaterial: "White gold",
    dialColor: "Blue aventurine",
    caseEnergy: "LUMEN",
    dialEnergy: "TIDE",
    signature: "Cosmic patience, reading time by a wandering star.",
    fact: "Its wandering-hours display revives a 17th-century complication AP reissued in the 1990s.",
    owned: true,
    rarity: 5,
    metal: "whiteGold",
    dialHex: "#1b2a5e",
    complication: "wandering",
  },
  {
    id: "lange-1-moonphase",
    brand: "A. Lange & Söhne",
    model: "Lange 1 Moonphase",
    reference: "192.032",
    caseMaterial: "Rose gold",
    dialColor: "Silver (argenté)",
    caseEnergy: "EMBER",
    dialEnergy: "TERRA",
    signature: "Warm precision; old-world order beneath a glowing night sky.",
    fact: "Its orbital moonphase stays accurate to one day's deviation over 122.6 years.",
    owned: true,
    rarity: 6,
    metal: "roseGold",
    dialHex: "#dcd6c8",
    complication: "moonphase",
  },
  {
    id: "daniel-roth-447",
    brand: "Daniel Roth",
    model: "Skeleton Chronograph",
    reference: "447.x.40",
    caseMaterial: "Yellow gold",
    dialColor: "Skeleton salmon",
    caseEnergy: "TERRA",
    dialEnergy: "EMBER",
    signature: "Baroque flair laid bare — mechanics worn as ornament.",
    fact: "Roth's double-ellipse case is among the most recognisable non-round forms in watchmaking.",
    owned: true,
    rarity: 4,
    metal: "yellowGold",
    dialHex: "#d9926a",
    complication: "skeleton",
  },
  {
    id: "chronoswiss-regulator",
    brand: "Chronoswiss",
    model: "Regulator",
    reference: "1988",
    caseMaterial: "Stainless steel",
    dialColor: "White",
    caseEnergy: "LUMEN",
    dialEnergy: "LUMEN",
    signature: "Disciplined separation — each hand granted its own stage.",
    fact: "Chronoswiss popularised the regulator as a wristwatch genre in the late 1980s.",
    owned: true,
    rarity: 9,
    metal: "steel",
    dialHex: "#efece4",
    complication: "regulator",
  },
  {
    id: "cw-bel-canto",
    brand: "Christopher Ward",
    model: "Bel Canto",
    caseMaterial: "Titanium",
    dialColor: "Salmon",
    caseEnergy: "VERDANT",
    dialEnergy: "EMBER",
    signature: "Unpretentious soul with a quiet chime of joy.",
    fact: "The Bel Canto brought a sonnerie au passage striking complication under £5,000.",
    owned: true,
    rarity: 10,
    metal: "titanium",
    dialHex: "#e29873",
    complication: "tourbillon",
  },
  {
    id: "breguet-3357ba",
    brand: "Breguet",
    model: "Classique Tourbillon",
    reference: "3357BA",
    caseMaterial: "Yellow gold",
    dialColor: "Silver (guilloché)",
    caseEnergy: "TERRA",
    dialEnergy: "LUMEN",
    signature: "Aristocratic stillness orbiting a slow mechanical heart.",
    fact: "Breguet patented the tourbillon in 1801; this guilloché dial is hand-engraved.",
    owned: true,
    rarity: 2,
    metal: "yellowGold",
    dialHex: "#d8d2c4",
    complication: "tourbillon",
  },

  // ---------- Iconic reference pool ----------
  {
    id: "rolex-sub-126610ln",
    brand: "Rolex",
    model: "Submariner Date",
    reference: "126610LN",
    caseMaterial: "Oystersteel",
    dialColor: "Black",
    caseEnergy: "LUMEN",
    dialEnergy: "TIDE",
    signature: "Unshakeable, all-weather resolve.",
    fact: "Its Cerachrom bezel insert is virtually scratchproof and UV-stable.",
    owned: false,
    rarity: 22,
    metal: "steel",
    dialHex: "#141414",
    complication: "dive",
  },
  {
    id: "patek-nautilus-5711",
    brand: "Patek Philippe",
    model: "Nautilus",
    reference: "5711/1A",
    caseMaterial: "Stainless steel",
    dialColor: "Blue",
    caseEnergy: "LUMEN",
    dialEnergy: "TIDE",
    signature: "Effortless prestige that never raises its voice.",
    fact: "Gérald Genta designed the Nautilus in 1976; the 5711 was discontinued in 2021.",
    owned: false,
    rarity: 4,
    metal: "steel",
    dialHex: "#1f3358",
    complication: "time",
  },
  {
    id: "omega-speedmaster",
    brand: "Omega",
    model: "Speedmaster Professional Moonwatch",
    reference: "310.30.42",
    caseMaterial: "Stainless steel",
    dialColor: "Black",
    caseEnergy: "LUMEN",
    dialEnergy: "TIDE",
    signature: "Mission-focused grit, forged for the extreme.",
    fact: "NASA flight-qualified the Speedmaster for all crewed missions in 1965.",
    owned: false,
    rarity: 24,
    metal: "steel",
    dialHex: "#161616",
    complication: "chronograph",
  },
  {
    id: "cartier-tank-louis",
    brand: "Cartier",
    model: "Tank Louis Cartier",
    reference: "WGTA0067",
    caseMaterial: "Yellow gold",
    dialColor: "Silver",
    caseEnergy: "TERRA",
    dialEnergy: "LUMEN",
    signature: "Refined intellect — elegance reduced to its essence.",
    fact: "The Tank's design was inspired by the Renault tanks of WWI, in 1917.",
    owned: false,
    rarity: 11,
    metal: "yellowGold",
    dialHex: "#ece9e0",
    complication: "time",
  },
  {
    id: "vc-overseas-4500v",
    brand: "Vacheron Constantin",
    model: "Overseas",
    reference: "4500V",
    caseMaterial: "Stainless steel",
    dialColor: "Blue",
    caseEnergy: "LUMEN",
    dialEnergy: "TIDE",
    signature: "Worldly calm, equally at home anywhere.",
    fact: "Founded in 1755, Vacheron is the oldest watch manufacturer in continuous operation.",
    owned: false,
    rarity: 8,
    metal: "steel",
    dialHex: "#21477e",
    complication: "time",
  },
  {
    id: "jlc-reverso-tribute",
    brand: "Jaeger-LeCoultre",
    model: "Reverso Tribute",
    reference: "Q3978480",
    caseMaterial: "Stainless steel",
    dialColor: "Blue (sunray)",
    caseEnergy: "LUMEN",
    dialEnergy: "TIDE",
    signature: "Two-faced poise — reserve that flips to reveal.",
    fact: "The Reverso's swivelling case was created in 1931 to protect polo players' crystals.",
    owned: false,
    rarity: 9,
    metal: "steel",
    dialHex: "#27416d",
    complication: "time",
  },
  {
    id: "gs-snowflake",
    brand: "Grand Seiko",
    model: "Snowflake",
    reference: "SBGA211",
    caseMaterial: "Titanium",
    dialColor: "White (textured)",
    caseEnergy: "VERDANT",
    dialEnergy: "LUMEN",
    signature: "Serene clarity, like fresh snow at first light.",
    fact: "Its Spring Drive glide-motion seconds hand sweeps without any ticking.",
    owned: false,
    rarity: 12,
    metal: "titanium",
    dialHex: "#f2f1ec",
    complication: "time",
  },
  {
    id: "hublot-big-bang-unico",
    brand: "Hublot",
    model: "Big Bang Unico",
    reference: "421.CI",
    caseMaterial: "Black ceramic",
    dialColor: "Skeleton",
    caseEnergy: "TIDE",
    dialEnergy: "VERDANT",
    signature: "Bold provocation — mechanics as raw statement.",
    fact: "Hublot's Art of Fusion pioneered modern ceramic-and-rubber luxury pairings.",
    owned: false,
    rarity: 14,
    metal: "ceramicBlack",
    dialHex: "#2a2a2e",
    complication: "skeleton",
  },
  {
    id: "panerai-luminor",
    brand: "Panerai",
    model: "Luminor Marina",
    reference: "PAM01312",
    caseMaterial: "Stainless steel",
    dialColor: "Black",
    caseEnergy: "LUMEN",
    dialEnergy: "TIDE",
    signature: "Stoic mass — presence you feel before you read it.",
    fact: "Its crown-protecting lever bridge dates to Panerai's mid-20th-century dive instruments.",
    owned: false,
    rarity: 19,
    metal: "steel",
    dialHex: "#141414",
    complication: "pilot",
  },
  {
    id: "vc-patrimony-platinum",
    brand: "Vacheron Constantin",
    model: "Patrimony",
    reference: "81180",
    caseMaterial: "Platinum",
    dialColor: "Silver",
    caseEnergy: "LUMEN",
    dialEnergy: "LUMEN",
    signature: "Understated gravity — the rarest metal, worn quietly.",
    fact: "Platinum is roughly 60% denser than 18k gold, giving a distinct heft.",
    owned: false,
    rarity: 5,
    metal: "platinum",
    dialHex: "#e4e2da",
    complication: "time",
  },
  {
    id: "lange-zeitwerk",
    brand: "A. Lange & Söhne",
    model: "Zeitwerk",
    reference: "140.029",
    caseMaterial: "Platinum",
    dialColor: "Black",
    caseEnergy: "LUMEN",
    dialEnergy: "TIDE",
    signature: "Mechanical patience that leaps, then waits.",
    fact: "The Zeitwerk's jumping digital display runs on a constant-force escapement.",
    owned: false,
    rarity: 3,
    metal: "platinum",
    dialHex: "#1a1a1d",
    complication: "digital",
  },
  {
    id: "iwc-big-pilot",
    brand: "IWC",
    model: "Big Pilot's Watch",
    reference: "IW501001",
    caseMaterial: "Stainless steel",
    dialColor: "Black",
    caseEnergy: "LUMEN",
    dialEnergy: "TIDE",
    signature: "Steady command — legibility as a form of calm.",
    fact: "Its 7-day movement traces to the oversized B-Uhr navigation watches of the 1940s.",
    owned: false,
    rarity: 17,
    metal: "steel",
    dialHex: "#161616",
    complication: "pilot",
  },
];
